name: Publish to Marketplace

on:
  release:
    types:
    - created
      
permissions:
  contents: read
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
